apiVersion: v1
kind: Pod
metadata:
  name: logs-pod
spec:
  containers:
    - name: debug-container
      image: busybox  
      command: ["/bin/sh", "-c", "sleep 3600"]  
      volumeMounts:
        - mountPath: /metrics  
          name: metrics-volume
  volumes:
    - name: metrics-volume
      persistentVolumeClaim:
        claimName: metrics-pvc  
  restartPolicy: Never
